config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index' 
  resources :items
  resources :users

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blocitoff_controller.rb
class BlocitoffController < ApplicationController

  def index
    @todos = Item.where(done: false)
    @todone = Item.where(done: true)
  end

  def new
    @todo = Item.new
  end

  def create
    @todo = Item.new(item_params)

    if @todo.save
      redirect_to item_index_path, :notice => "New item added!"
    else
      render 'new'
    end
  end

  def update
    @todo = Item.find(params[:id])
    if @todo.update_attribute(:done, true)
      redirect_to item_index_path, :notice => "Item marked as done!"
    else
      redirect_to item_index_path, :notice => "Unable to be marked as done!"
    end
  end

  def destroy
    @todo = Item.find(params[:id])
    @todo.destroy

    redirect_to item_index_path, :notice => "Item deleted!"
  end

  private
  def item_params
    params.require(:item).permit(:description, :done)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    if user_signed_in?
      redirect_to user_url(current_user)
    else
      redirect_to new_user_session_url
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @todos = Item.where(done: false)
    @todone = Item.where(done: true)
    @user = current_user
  end

  def new
    @todo = Item.new
  end


  def create
		@todo = Item.create(item_params)
		redirect_to '/items#index'
	end

  def edit
    @todo = Item.find(params[:id])
  end

  def update
    @todo = Item.find(params[:id])
    if @todo.update(item_params)
      redirect_to items_url, :notice => "Item Updated"
    else
      redirect_to items_url, :notice => "Could not update Item"
    end
  end

  def destroy
    @todo = Item.find(params[:id])
    @todo.destroy

    redirect_to items_url, :notice => "Item deleted!"
  end

  private
  def item_params
    params.require(:item).permit(:description, :done)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #after_action :user_signed_in?, only: :show
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocitoff_helper.rb
module BlocitoffHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blocitoff/index.html.erb
<h1>Blocitoff items</h1>

<h2>TO DO:</h2>

<% @todos.each do |t| %>
  <p>
    <strong><<%= t.description %></strong>
    <small><%= link_to "Mark as done", blocitoff_path(t), :method => :put %></small>
  </p>
<% end %>


<h2>DONE TODOS:</h2>

<% @todone.each do |t| %>
  <p>
    <strong><<%= t.description %></strong>
    <small><%= link_to "Remove", t, :confirm => "It is ok to remove item from list?", :method => :delete %></small>
  </p>
<% end %>



<p><%= link_to "Add new TODO", new_blocitoff_path %></p>

app/views/blocitoff/new.html.erb
<h1>Add new TO DO</h1>

<% form_for @todo, :url => blocitoff_path(@todo) do |f| %>
  <%= f.label :description %>: <%= f.text_field :description %>
  <%= f.hidden_field :done, :value => false %>
  <%= f.submit "Add new TODO" %>
<% end %>

app/views/items/_form.html.erb
<h1>Edit To Do</h1>

<%= form_for @todo do |f| %>
  <%= f.label :description %>: <%= f.text_field :description %>
  <%= f.hidden_field :done, :value => false %>
  <%= f.submit "Edit To Do" %>
<% end %>

app/views/items/_todo.html.erb
<p>
  <strong><%= todo.description %></strong>
  <%= distance_of_time_in_words(Time.now, todo.created_at + 7.days) %>
  to go...
  <small><%= link_to 'Edit', edit_item_path(todo) %></small>
  <small><%= link_to "Mark as done", item_path(id: todo.id, item: {done: true}), action: 'update', method: 'put', class: 'glyphicon glyphicon-ok' %></small>
</p>

app/views/items/edit.html.erb
<h1 class="todo_list_title">Edit To Do</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', items_path %>
</div>

app/views/items/index.html.erb
<h1>Blocitoff items</h1>
<%= link_to "Back to My Profile", user_path(@user) %></br>
<h2>TO DO:</h2>

<%= render partial: "todo", collection: @todos %>

<h2>DONE TODOS:</h2>

<% @todone.each do |t| %>
  <p>
    <strong><%= t.description %></strong>
    <small><%= link_to "Remove", t, :confirm => "It is ok to remove item from list?", :method => :delete %></small>
  </p>
<% end %>



<p><%= link_to "Add To Do", new_item_path %></p>

app/views/items/new.html.erb
<h1>Add To Do</h1>

<%= form_for @todo do |f| %>
  <%= f.label :description %>: <%= f.text_field :description %>
  <%= f.hidden_field :done, :value => false %>
  <%= f.submit "Add To Do" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  You are currently signed in as <%= current_user.email %>. Not you?
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Sign up!", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
<% end %>

<% flash.each do |name, message| %>
  <%= content_tag :div, message, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/lists/index.html.erb
<h1>Blocitoff items</h1>

<h2>TO DO:</h2>

<% @todos.each do |t| %>
  <p>
    <strong><<%= t.description %></strong>
    <small><%= link_to "Mark as done", edit_item_path(t), :method => :put %></small>
  </p>
<% end %>


<h2>DONE TODOS:</h2>

<% @todone.each do |t| %>
  <p>
    <strong><<%= t.description %></strong>
    <small><%= link_to "Remove", t, :confirm => "It is ok to remove item from list?", :method => :delete %></small>
  </p>
<% end %>



<p><%= link_to "Add new TODO", new_item_path %></p>

app/views/users/show.html.erb
<h1>Hello!</h1>
<p>Your e-mail address: </br></br><%= @user.email %></p>
<%= link_to "See My Todo List", items_path %>